### ISSUE TITLE
Inquire: Was acgan-minst.py written in GPU setting or CPU setting

### ISSUE THREAD

**Issue by Samt7** [MLEnthusiast/acgan-mnist#1]
@MLEnthusiast
I am facing this problem 
ValueError: Tensor("Generator.1.Linear/Generator.1.Linear.W:0", shape=(2, 512), dtype=float32_ref) must be from the same graph as Tensor("Neg:0", shape=(), dtype=float32).
ValueError: Tensor("Generator.1.Linear/Generator.1.Linear.b:0", shape=(512,), dtype=float32_ref) must be from the same graph as Tensor("Generator.1.Linear/MatMul:0", shape=(256, 512), dtype=float32).

Any gudience to solve the problem?

**Comment by MLEnthusiast** [comment]
@Samt7 this is written to be run on a CPU.
